
#General Magical Forest Biome Configuration
[general]
	#[WIP, heavily untested] Magical Forest Hills spawn weight in Overworld. The lower the number, the rarer is the biome!
	#Range: > 1
	biomeWeightHills = 12
	#[WIP, heavily untested] Magical Forest spawn weight in Overworld. The lower the number, the rarer is the biome!
	#Range: > 1
	biomeWeightForest = 20

